### ISSUE TITLE
AMP Readiness Tool - 404 page

### ISSUE THREAD

**Issue by AsimTariq** [ampproject/amp-readiness#20]
**Current behavior**
The plugin AMP Readiness has a link "AMP Readiness Tool" that is leading to This page that gives 404.

**Screenshots/videos:**
![image](https://user-images.githubusercontent.com/5482516/75143030-903ac100-56f4-11ea-890b-7cece51a94dd.png)

**Expected behavior/code**
Github-page that is working

**Reproduction procedure**
1. Right Click on the extension (in Chrome)
2. Click on "AMP Readiness Tool"
3. Shows 404-page in Github

What browser are you using? **Chrome**
What O/S are you using? **Windows 10**

**Comment by philkrie** [comment]
thanks for opening. we changed repos and forgot to update.

**Comment by philkrie** [comment]
fixed, will deploy later this month
